github:
  branch_name: main
  tooling_branch_name: main
github_actions:
    self_hosted: true
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
  version_updates:
    sources:
      - githubreleases
conda_build_tool: rattler-build
azure:
  max_parallel: 25
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
provider:
  linux_64: github_actions
