github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
conda_build_tool: rattler-build
azure:
  max_parallel: 25
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
